on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    name: ${{ matrix.os }} with python-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.14"]

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v7

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}

      # TODO:
      # https://github.com/pypa/hatch/pull/1922
      # Wait until hatch release supports dependencies from dependency-groups
      - name: Hatch - checkout master
        uses: actions/checkout@v5
        with:
          repository: pypa/hatch.git
          ref: master
          path: ./.build_deps/hatch

      - name: Hatch - install
        run: |
          uv pip install --system ./.build_deps/hatch

      - name: Cache hatch data
        uses: actions/cache@v4
        with:
          path: ~/.local/share/hatch
          key: ${{ runner.os }}-hatch-${{ hashFiles('**/pyproject.toml') }}

      - name: Create generated files
        run: |
          hatch build -t wheel

      - name: Lint and check format
        run: |
          hatch run dev:ruff check .
          hatch run dev:mypy .

      - name: Test
        run: |
          hatch run dev:pytest
